spring:
  datasource:
    url: jdbc:postgresql://localhost:5432
    username: postgres
    password: PG123User
  http:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2500MB
edhd:
  adminPassword: ADMIN123User
  dbName: edhd
  storageDir: /home/hduser/tmp
  threads: 20
  hadoop:
    defaultFS: hdfs://hadoop-master:54310
    hduser: hduser
    hdfsFilePreview: 20